### ISSUE TITLE
October release notes

### ISSUE THREAD

**Issue by olegmoz** [artipie/blog.artipie.com#7]
We need to publish October release notes article to give overview of changes made in Artipie during the month

**Comment by olenagerasimova** [comment]
@olegmoz could you please unload the list of closed issues for this month for me?

**Comment by olegmoz** [comment]
@olenagerasimova sure, here is list for last 30 days (may include some issues from late September):

 - #359 - use StorageHasRepoMd: https://github.com/artipie/rpm-adapter/pull/371
 - #359 - Verify repomd.xml: https://github.com/artipie/rpm-adapter/pull/370
 - #368 - Upgraded HTTP to 0.16.7, migrated to BasicAuthSlice: https://github.com/artipie/rpm-adapter/pull/369
 - #144 - Change docker image: https://github.com/artipie/npm-adapter/pull/146
 - #140 - HTTP upgraded to 0.16.7, migrated to BasicAuthSlice: https://github.com/artipie/npm-adapter/pull/145
 - #141 - NpmProxyITCase disabled: https://github.com/artipie/npm-adapter/pull/143
 - #141 - Use TestResource in NpmIT: https://github.com/artipie/npm-adapter/pull/142
 - #137 - Integration tests enabled, NpmCommandsTest renamed to NpmIT: https://github.com/artipie/npm-adapter/pull/138
 - #89 - Fix NpmProxyITCase: https://github.com/artipie/npm-adapter/pull/136
 - #89 - Use PublisherAs instead of Concatenation: https://github.com/artipie/npm-adapter/pull/135
 - #119 - Fix `time` field in meta.json: https://github.com/artipie/npm-adapter/pull/134
 - #119 - Add disabled test for time in meta.json: https://github.com/artipie/npm-adapter/pull/133
 - #129 - Fix NPM publish test: https://github.com/artipie/npm-adapter/pull/132
 - #127 - Use testContainer: https://github.com/artipie/npm-adapter/pull/131
 - #123 - Moved proxy docs to root README.md with some modifications: https://github.com/artipie/npm-adapter/pull/130
 - #123 - Moved proxy code to root: https://github.com/artipie/npm-adapter/pull/128
 - #122 - Fixed & refactored NpmCommandsTest: https://github.com/artipie/npm-adapter/pull/126
 - #124 - Removed codecov upload phase from maven.yml: https://github.com/artipie/npm-adapter/pull/125
 - #284 - cache impl to load from remote: https://github.com/artipie/asto/pull/285
 - #605 - Verify with authentication in npmIT: https://github.com/artipie/artipie/pull/721
 - #700 - Deprecated classes usage removed in SliceFromConfig: https://github.com/artipie/artipie/pull/720
 - #715 - pypi proxy IT: https://github.com/artipie/artipie/pull/719
 - #605 - Verify publish in NpmITCase: https://github.com/artipie/artipie/pull/717
 - #714 - pypi proxy: https://github.com/artipie/artipie/pull/716
 - #605 - npmInstall ITCase: https://github.com/artipie/artipie/pull/710
 - #700 - Deprecated classes usage removed in AuthAndPermissionsTest: https://github.com/artipie/artipie/pull/709
 - #694 - HTTP upgrade for fixed GroupSlice: https://github.com/artipie/artipie/pull/708
 - #692 - Extracted FileProxy and supported auth: https://github.com/artipie/artipie/pull/707
 - #693 - Updated Maven proxy cache config format: https://github.com/artipie/artipie/pull/705
 - #692 - Added FileProxyAuthIT: https://github.com/artipie/artipie/pull/704
 - #694 - Support for multiple remotes in Maven proxy: https://github.com/artipie/artipie/pull/703
 - #693 - Added cache method to ProxyConfig: https://github.com/artipie/artipie/pull/702
 - #690 - use CredsConfigYaml, correct Users.FromStorageYaml and readme: https://github.com/artipie/artipie/pull/699
 - #693 - Docker upgraded to 0.4.8: https://github.com/artipie/artipie/pull/698
 - #693 - Using proxy config in Docker proxy: https://github.com/artipie/artipie/pull/696
 - #690 - use CredsConfigYaml: https://github.com/artipie/artipie/pull/695
 - #690 - CredsConfigYaml created: https://github.com/artipie/artipie/pull/691
 - #608 - Updated docs for maven proxy configuration: https://github.com/artipie/artipie/pull/689
 - #677 - Add ctor with port in ArtipieServer: https://github.com/artipie/artipie/pull/688
 - #608 - Using RepoConfig in MavenProxy: https://github.com/artipie/artipie/pull/687
 - #633 - Response 404 to request not related to repos: https://github.com/artipie/artipie/pull/686
 - #608 - ProxyRepoConfig and YamlProxyRepoConfig: https://github.com/artipie/artipie/pull/685
 - #674 - Using GenericAuthenticator in MavenProxy: https://github.com/artipie/artipie/pull/683
 - #652 - Verify with authentication in pypiIT: https://github.com/artipie/artipie/pull/682
 - #680 - separate profile for IT: https://github.com/artipie/artipie/pull/681
 - #602 - NuGet tests disabled: https://github.com/artipie/artipie/pull/678
 - #660 - use RepoConfigYaml instead of RepoPerms: https://github.com/artipie/artipie/pull/676
 - #602 - Verify install nugetIT: https://github.com/artipie/artipie/pull/675
 - #338 - HTTP upgraded to 0.16.5: https://github.com/artipie/docker-adapter/pull/340
 - #338 - Using HTTP client auth: https://github.com/artipie/docker-adapter/pull/339
 - Update http to 0.16.2: https://github.com/artipie/docker-adapter/pull/337
 - #256 - Group slice error handling: https://github.com/artipie/http/pull/257
 - #253 - added header value regex to RtRule.ByHeader: https://github.com/artipie/http/pull/255
 - #253 - RtRule.ByHeader created: https://github.com/artipie/http/pull/254
 - #251 - StatefulResponse renamed to CachedResponse and fixed: https://github.com/artipie/http/pull/252
 - #249 - Authentication.Anonymous created: https://github.com/artipie/http/pull/250
 - #247 - created BasicAuthSlice: https://github.com/artipie/http/pull/248
 - #211 - Fix rsStatus of head, add disabled test for MavenProxySliceIT: https://github.com/artipie/maven-adapter/pull/218
 - Updated http and http-client: https://github.com/artipie/maven-adapter/pull/217
 - #215 - remove unused classes and update asto: https://github.com/artipie/maven-adapter/pull/216
 - #212 - HeadProxySlice unit test: https://github.com/artipie/maven-adapter/pull/214
 - #212 - HeadProxySlice fixed: https://github.com/artipie/maven-adapter/pull/213
 - #204 - Authentication support in proxy: https://github.com/artipie/maven-adapter/pull/210
 - #138 - Using UriClientSlice in proxy: https://github.com/artipie/maven-adapter/pull/205
 - #197 - Add MavenProxyITCase: https://github.com/artipie/maven-adapter/pull/203
 - #197 - fixed and tested RepoHead and MavenProxySlice: https://github.com/artipie/maven-adapter/pull/202
 - #135 - search fully implemented: https://github.com/artipie/pypi-adapter/pull/144
 - #135 - artifact was found on search: https://github.com/artipie/pypi-adapter/pull/143
 - #130 - added test for proxy auth: https://github.com/artipie/pypi-adapter/pull/142
 - #129 - headers for cached items in ProxySlice: https://github.com/artipie/pypi-adapter/pull/141
 - #135 - artifact not found branch: https://github.com/artipie/pypi-adapter/pull/140
 - #129 - test for proxy with pip: https://github.com/artipie/pypi-adapter/pull/139
 - #135 - read summary from metadata: https://github.com/artipie/pypi-adapter/pull/138
 - #135 - project name from xml: https://github.com/artipie/pypi-adapter/pull/137
 - #135 - test for search command: https://github.com/artipie/pypi-adapter/pull/136
 - #128 - added IndexProxySliceTest: https://github.com/artipie/pypi-adapter/pull/134
 - #128 - IndexProxySlice created: https://github.com/artipie/pypi-adapter/pull/133
 - #131 - update http: https://github.com/artipie/pypi-adapter/pull/132
 - #126 - proxy index request: https://github.com/artipie/pypi-adapter/pull/127
 - Enable logs for tests: https://github.com/artipie/gem-adapter/pull/80
 - Bumped http and ppom: https://github.com/artipie/gem-adapter/pull/75
 - #1 - Dependencies bump: https://github.com/artipie/vertx-server/pull/28
 - Resolve conflict between tf and cl headers: https://github.com/artipie/vertx-server/pull/27
 - #40 - Sending empty headers and body to remote in Proxy: https://github.com/artipie/files-adapter/pull/41
 - #37 - Authentication support in proxy: https://github.com/artipie/files-adapter/pull/39
 - #37 - HTTP client upgrade, UriClientSlice usage: https://github.com/artipie/files-adapter/pull/38
 - #72 - HTTP upgraded to 0.16.7, migrated to BasicAuthSlice: https://github.com/artipie/helm-adapter/pull/73
 - #25 - JettyClientSlices.client() method removed: https://github.com/artipie/http-client/pull/70
 - #51 - Bearer support in GenericAuthenticator: https://github.com/artipie/http-client/pull/69
 - #51 - Params and auth for token request in BearerAuthenticator: https://github.com/artipie/http-client/pull/68
 - #66 - Copying request body inside AuthClientSlice: https://github.com/artipie/http-client/pull/67
 - #51 - Added BearerAuthenticator: https://github.com/artipie/http-client/pull/65
 - #51 - Added TokenFormat and OAuthTokenFormat: https://github.com/artipie/http-client/pull/64
 - #51 - Authenticator changed to by async: https://github.com/artipie/http-client/pull/63
 - #50 - AuthClientSlice and UriClientSlice documented: https://github.com/artipie/http-client/pull/62
 - #50 - Anonymous Authenticator and it's support in AuthClientSlice: https://github.com/artipie/http-client/pull/61
 - #50 - Fixed issue with AuthClientSlice closing response before handled: https://github.com/artipie/http-client/pull/60
 - #50 - Added GenericAuthenticator: https://github.com/artipie/http-client/pull/59
 - #67 - Fixed stop order in HttpServer to prevent possible hang ups: https://github.com/artipie/http-client/pull/58
 - #33 - Added UriClientSlice: https://github.com/artipie/http-client/pull/56
 - #50 - AuthClientSlice added: https://github.com/artipie/http-client/pull/55
 - #33 - Added PathPrefixSlice: https://github.com/artipie/http-client/pull/54
 - #50 - Added Authenticator and Authenticator.Basic: https://github.com/artipie/http-client/pull/53
 - IT case with client slices and vertx: https://github.com/artipie/http-client/pull/49
 - #5 - september release notes: https://github.com/artipie/blog.artipie.com/pull/6
