### ISSUE TITLE
Write blog post about python

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/blog.artipie.com#9]
At university, I wrote a lot of python scripts to perform some calculations and visualize some data. Usually, I was not allowed to open the repository and was forced to develop/stash everything locally. 
Now, github provides pro accounts for students with the opportunity to create private repos and with the help of Artipie central it's possible to publish python artifacts and stash some data in binary repository privately. 
That's the premise for the blog post. 

I'm planning to create simple python repo with some visualization script, visualization data (large csv/binary file) will be stored in binary repo of Artipie central, python repository will be published (using CD) to Artipie central. After that it should be possible to install python artifact locally, run it and see the plot.

The blog post will describe the whole process and, maybe, I'll manage to come up with some fun university story as a preamble.  

Let's divide the job into several parts:

- [ ] Part one https://github.com/artipie/blog.artipie.com/issues/12

**Comment by olenagerasimova** [comment]
@olegmoz what do you think? It could be part of the plan for the second week of November.

**Comment by olegmoz** [comment]
@olenagerasimova sounds great! Guess we can plan it for week 47 if you will have some draft by the end of next week
